#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Ofcold\Configuration\LoaderConfiguration;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Config\Repository;

$loader = new LoaderConfiguration(
	$config = new Repository,
	new Filesystem
);

$loader->addNamespace('test', __DIR__ . '/tests/config');

print_r($config->all());

$loader->addNamespaceOverrides('test', __DIR__ . '/tests/overrides');

print_r($config->all());